services:
  docker-ckpool:
    image: docker-ckpool
    ports:
      - 3333:3333
    extra_hosts:
      - ckpool.local:host-gateway
    volumes:
      - /home/umbrel/umbrel/app-data/ckpool/conf:/srv/ckpool/conf
      - /home/umbrel/umbrel/app-data/ckpool/logs:/srv/ckpool/logs
    restart: on-failure
